Fai 1055 application create jobs page
SkillsFundingAgency/das-findapprenticeship-web pull request #24
Opened 2024-01-23 21:48 UTC by balaji-j

2024-01-24 19:37 UTC, dashton82 requested changes

2024-01-24 19:37 UTC, dashton82 commented on src/SFA.DAS.FAA.Web/Models/Apply/AddWorkHistoryRequest.cs
> +        [FromRoute] public required string VacancyReference { get; init; }
this bit we wont need 👍🏻

2024-01-24 19:37 UTC, dashton82 commented on src/SFA.DAS.FAA.Web/Controllers/Apply/WorkHistoryController.cs
> +        [Route("vacancies/{vacancyReference}/apply/workhistory/{applicationId}", Name = RouteNames.ApplyApprenticeship.WorkHistory)]
```suggestion
        [Route("apply/{applicationId}/workhistory/", Name = RouteNames.ApplyApprenticeship.WorkHistory)]
```
i think maybe this?

2024-01-24 19:37 UTC, dashton82 commented on src/SFA.DAS.FAA.Web/Controllers/Apply/WorkHistoryController.cs
> +        [Route("vacancies/{vacancyReference}/apply/workhistory/{applicationId}", Name = RouteNames.ApplyApprenticeship.WorkHistory)]
```suggestion
        [Route("apply/{applicationId}/workhistory", Name = RouteNames.ApplyApprenticeship.WorkHistory)]
```

2024-01-25 14:11 UTC, balaji-j commented on src/SFA.DAS.FAA.Web/Views/Apply/WorkHistory/List.cshtml
> +@if (Model.ErrorDictionary!.Any())
Replaced with Partial view and also added the hyperlink so that on click of error message, it jumps to the error field.

2024-01-25 14:11 UTC, balaji-j commented on src/SFA.DAS.FAA.Web/Models/Apply/AddWorkHistoryRequest.cs
> +        [FromRoute] public required string VacancyReference { get; init; }
Removed the extra property

2024-01-25 14:12 UTC, balaji-j commented on src/SFA.DAS.FAA.Web/Controllers/Apply/WorkHistoryController.cs
> +        [Route("vacancies/{vacancyReference}/apply/workhistory/{applicationId}", Name = RouteNames.ApplyApprenticeship.WorkHistory)]
Replaced the route as suggested.

2024-01-25 14:12 UTC, balaji-j commented on src/SFA.DAS.FAA.Web/Controllers/Apply/WorkHistoryController.cs
> +        [Route("vacancies/{vacancyReference}/apply/workhistory/{applicationId}", Name = RouteNames.ApplyApprenticeship.WorkHistory)]
Replaced the route as suggested

2024-01-25 14:17 UTC, balaji-j commented on src/SFA.DAS.FAA.Web/Validators/AddWorkHistoryRequestValidator.cs
> +                .WithMessage(VacancyReferenceNotNumeric);
Removed the FluentValidation for the AddWorkHistoryRequest Model

2024-01-25 17:46 UTC, dashton82 approved these changes

2024-01-25 20:35 UTC, chrisfoster76 commented
I see Dan has approved this, but now that I've come to add my Add a Job page, I've spotted a few things that might need to be looked at. A quick list:

1. Answering the "Do you want to add a job?" question marks both the Jobs and Volunteering and work experience sections as Complete or Incomplete. It should only mark the Jobs section. (I believe the issue is actually with the outer api branch rather than this one, strictly speaking).
2. The "Do you want to add a job?" page is not wired in from the task list. I couldn't do this in advance without deciding on the route for every sub page and then adding in NotImplemented controller actions, so I chose to leave it to the developer of each page to update the task list accordingly.
3. I _think_ the uri should change from "apply" to "applications", since nouns should be favoured above verbs (Dan might think otherwise though, so you may wish to check with him). I know we've been over it at least twice. :-)
4. On validation failure, there's a bonus error message in the header which shouldn't be there
5. On validtion failure, the back link ceases to work
6. In the Get action of the WorkHistoryController, the _request_ object also appears to be the _viewmodel_ - is this deliberate, as I think they have separate concerns.

Thanks and sorry!

2024-01-30 09:47 UTC, dashton82 approved these changes

2024-01-30 13:44 UTC, merged