FAI-1091 Create the 'Add a training course' page
SkillsFundingAgency/das-findapprenticeship-web pull request #33
Opened 2024-02-08 12:08 UTC by SarahDuncan

2024-02-09 13:49 UTC, chrisfoster76 requested changes

2024-02-09 13:49 UTC, chrisfoster76 commented on src/SFA.DAS.FAA.Web/Controllers/Apply/WorkHistoryController.cs
> +            var viewModel = new AddTrainingCourseViewModel
I think this _might_ have been done in error.

2024-02-09 14:03 UTC, chrisfoster76 approved these changes

2024-02-13 14:03 UTC, dashton82 approved these changes

2024-02-13 14:06 UTC, merged