Fai-913 create location selection page
SkillsFundingAgency/das-findapprenticeship-web pull request #5
Opened 2023-10-19 07:58 UTC by A-J-Wright

2023-10-19 08:07 UTC, SarahDuncan commented on src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Location.cshtml
James King has changed the html of the page quite a bit in the new 943 branch. I don't know if that needs to be brought into this branch or we can just leave it to be tested when 943 is tested? @dashton82

2023-10-19 12:25 UTC, dashton82 requested changes
All good, just a few minor changes

2023-10-19 12:25 UTC, dashton82 commented on src/SFA.DAS.FAA.Web.AcceptanceTests/Steps/HttpSteps.cs
> +    //not sure if this is right
Is it right? 😀

2023-10-19 12:25 UTC, dashton82 commented on src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Location.cshtml
Yep bring in if you already haven't done so

2023-10-19 12:25 UTC, dashton82 commented on src/SFA.DAS.FAA.Web/Models/BrowseByInterestViewModel.cs
> +    private static bool SetPreviouslySelected(List<string>? previouslySelectedValues, int routeId)
I think we need some tests to cover this in the view model test

2023-10-22 16:44 UTC, dashton82 submitted a review, later dismissed

2023-10-23 12:50 UTC, SarahDuncan submitted a review, later dismissed

2023-10-24 09:22 UTC, SarahDuncan approved these changes

2023-10-24 09:53 UTC, chrisfoster76 approved these changes

2023-10-24 09:55 UTC, merged